site_name: Gluu Server Cookbook 
site_description: An SSO, Federation and API Access Management suite
site_favicon: '/img/gluu_favicon.ico'
copyright: Copyright &copy; 2014, Gluu, Inc.
docs_dir: sources
repo_url: https://github.com/GluuFederation/docs
theme: spacelab 

pages:
- ['index.md', 'Home']

- ['reference/configuraion/index.md', 'Reference', 'Configuration']
- ['reference/ldap/index.md', 'Reference', 'LDAP Schema']
- ['reference/api/index.md', 'Reference', 'API']
- ['reference/interception/index.md', 'Reference', 'Interception Scripts']
- ['reference/lib/index.md', 'Reference', 'Libraries']

- ['admin-guide/installation/index.md', 'Admin Guide', 'Installation']
- ['admin-guide/certificates/index.md', 'Admin Guide', 'Certificates']
- ['admin-guide/interception-scripts/index.md', 'Admin Guide', 'Interception Scripts']
- ['admin-guide/authentication/index.md', 'Admin Guide', 'Authentication']
- ['admin-guide/configuration/index.md', 'Admin Guide', 'Configuration']
- ['admin-guide/user-management/index.md', 'Admin Guide', 'User Management']
- ['admin-guide/device-management/index.md', 'Admin Guide', 'Device Management']
- ['admin-guide/saml/index.md', 'Admin Guide', 'SAML']
- ['admin-guide/openid-connect/index.md', 'Admin Guide', 'OpenID Connect']
- ['admin-guide/uma/index.md', 'Admin Guide', 'UMA']
- ['admin-guide/multiparty-federation/index.md', 'Admin Guide', 'MultiParty Federation']

- ['articles/apache-saml/index.md', 'Articles', 'Apache SAML']
- ['articles/apache-oauth2/index.md', 'Articles', 'Apache OAuth2']
- ['articles/nginx-oauth2/index.md', 'Articles', 'nginx OAuth2']
- ['articles/java-connect/index.md', 'Articles', 'Java OpenID Connect']
- ['articles/java-saml/index.md', 'Articles', 'Java SAML']
- ['articles/js-connect/index.md', 'Articles', 'Javascript OpenID Connect']
- ['articles/scim-client/index.md', 'Articles', 'SCIM client']

# Sub pages of User-Management
- ['admin-guide/user-management/scim/index.md', '', '']
- ['admin-guide/user-management/ldap-sync/index.md', '', '']
- ['admin-guide/user-management/local-admin/index.md', '', '']

# Sub pages of SAML
- ['admin-guide/saml/outbound-saml/index.md', '', '']
- ['admin-guide/saml/inbound-saml/index.md', '', '']

# Sub Pages of OpenID Connect
- ['admin-guide/openid-connect/registration/index.md', '', '']
- ['admin-guide/openid-connect/discovery/index.md', '', '']
- ['admin-guide/openid-connect/scopes/index.md', '', '']
- ['admin-guide/openid-connect/client-config/index.md', '', '']

 
