site_name: Gluu Server
site_description: An SSO, Federation and API Access Management suite
site_favicon: '/img/gluu_favicon.ico'
copyright: Copyright &copy; 2014, Gluu, Inc.
docs_dir: sources
repo_url: https://github.com/GluuFederation/docs
theme: spacelab 

pages:

# Home Page
- ['./index.md', 'Home']

# Admin Guide Sections
- ['admin-guide/introduction/index.md', 'Admin Guide', 'introduction']
- ['admin-guide/installation/index.md', 'Admin Guide', 'Installation']
- ['admin-guide/configuration/index.md', 'Admin Guide', 'Configuration']
- ['admin-guide/custom-look/index.md', 'Admin Guide', 'Customizing Look and Feel']
- ['admin-guide/certificates/index.md', 'Admin Guide', 'Certificates']
- ['admin-guide/user-management/index.md', 'Admin Guide', 'User Management']
- ['admin-guide/authentication/index.md', 'Admin Guide', 'Authentication']
- ['admin-guide/saml/index.md', 'Admin Guide', 'SAML']
- ['admin-guide/openid-connect/index.md', 'Admin Guide', 'OpenID Connect']
- ['admin-guide/uma/index.md', 'Admin Guide', 'UMA']
- ['admin-guide/interception-scripts/index.md', 'Admin Guide', 'Interception Scripts']
- ['admin-guide/multiparty-federation/index.md', 'Admin Guide', 'MultiParty Federation']
- ['admin-guide/oxPush/index.md', 'Admin Guide', 'oxPush']

# Reference sections
- ['reference/configuration/index.md', 'Reference', 'Configuration']
- ['reference/oxTrust/index.md', 'Reference', 'oxTrust User Interface']
- ['reference/ldap/index.md', 'Reference', 'LDAP Schema']
- ['reference/lib/index.md', 'Reference', 'Libraries']
- ['reference/api/index.md', 'Reference', 'APIs']

# Articles
- ['articles/apache-saml.md', 'Articles', 'Apache SAML']
- ['articles/java-saml.md', 'Articles', 'Java SAML']
- ['articles/apache-oauth2.md', 'Articles', 'Apache OpenID Connect / UMA']
- ['articles/nginx-oauth2.md', 'Articles', 'nginx OpenID Connect / UMA']
- ['articles/js-connect.md', 'Articles', 'JavaScript OpenID Connect RP']
- ['articles/java-connect.md', 'Articles', 'Java OpenID Connect RP']
- ['articles/scim-client.md', 'Articles', 'Java SCIM client']
- ['articles/mobile-api.md', 'Articles', 'Mobile - Headless API : Connect / UMA']

