site_name: Gluu Server
site_description: An SSO, Federation and API Access Management suite
site_favicon: '/img/gluu_favicon.ico'
copyright: Copyright &copy; 2014, Gluu, Inc.
docs_dir: sources
repo_url: https://github.com/GluuFederation/docs
theme: spacelab 

pages:

# Articles
- ['articles/apache-saml/index.md', 'Articles', 'Apache SAML']
- ['articles/apache-oauth2/index.md', 'Articles', 'Apache OAuth2']
- ['articles/nginx-oauth2/index.md', 'Articles', 'nginx OAuth2']
- ['articles/java-connect/index.md', 'Articles', 'Java OpenID Connect']
- ['articles/java-saml/index.md', 'Articles', 'Java SAML']
- ['articles/js-connect/index.md', 'Articles', 'Javascript OpenID Connect']
- ['articles/scim-client/index.md', 'Articles', 'SCIM client']

# Reference sections
- ['reference/configuration/index.md', 'Reference', 'Configuration']
- ['reference/ldap/index.md', 'Reference', 'LDAP Schema']
- ['reference/lib/index.md', 'Reference', 'Libraries']
- ['reference/api/index.md', 'Reference', 'APIs']

# Sub pages of Reference / Library
- ['reference/lib/openid-connect.md', '', '']
- ['reference/lib/uma.md', '', '']
- ['reference/lib/scim.md', '', '']
- ['reference/lib/saml.md', '', '']
- ['reference/lib/user-management.md', '', '']

# Sub pages of Reference / LDAP
- ['reference/ldap/schema.md', '', '']
- ['reference/ldap/namespace.md', '', '']
- ['reference/ldap/indexing.md', '', '']
- ['reference/ldap/replication.md', '', '']

# Sub pages of Reference / Configuration
- ['reference/configuration/system.md', '', '']
- ['reference/configuration/oxAuth.md', '', '']
- ['reference/configuration/oxTrust.md', '', '']
- ['reference/configuration/shibIDP.md', '', '']
- ['reference/configuration/asimba.md', '', '']
- ['reference/configuration/opendj.md', '', '']
- ['reference/configuration/openldap.md', '', '']
- ['reference/configuration/jagger.md', '', '']
- ['reference/configuration/oxPush.md', '', '']
- ['reference/configuration/oxProx.md', '', '']
- ['reference/configuration/mysql.md', '', '']
- ['reference/configuration/memcached.md', '', '']

# Admin Guide Sections
- ['admin-guide/installation/index.md', 'Admin Guide', 'Installation']
- ['admin-guide/configuration/index.md', 'Admin Guide', 'Configuration']
- ['admin-guide/certificates/index.md', 'Admin Guide', 'Certificates']
- ['admin-guide/user-management/index.md', 'Admin Guide', 'User Management']
- ['admin-guide/authentication/index.md', 'Admin Guide', 'Authentication']
- ['admin-guide/saml/index.md', 'Admin Guide', 'SAML']
- ['admin-guide/openid-connect/index.md', 'Admin Guide', 'OpenID Connect']
- ['admin-guide/uma/index.md', 'Admin Guide', 'UMA']
- ['admin-guide/interception-scripts/index.md', 'Admin Guide', 'Interception Scripts']
- ['admin-guide/multiparty-federation/index.md', 'Admin Guide', 'MultiParty Federation']
- ['admin-guide/oxPush/index.md', 'Admin Guide', 'oxPush']

# Sub Pages of Admin Guide / installation
- ['admin-guide/installation/redhat.md', '', '']
- ['admin-guide/installation/ubuntu.md', '', '']
- ['admin-guide/installation/centos.md', '', '']
- ['admin-guide/installation/debian.md', '', '']
- ['admin-guide/installation/windows.md', '', '']
- ['admin-guide/installation/mac.md', '', '']
- ['admin-guide/installation/juju.md', '', '']
- ['admin-guide/installation/build.md', '', '']

# Sub Pages of Admin Guide / Configuration
- ['admin-guide/configuration/asimba.md', '', '']
- ['admin-guide/configuration/oxAuth.md', '', '']
- ['admin-guide/configuration/oxPush.md', '', '']
- ['admin-guide/configuration/oxTrust.md', '', '']
- ['admin-guide/configuration/shibIDP.md', '', '']
- ['admin-guide/configuration/oxProx.md', '', '']

# Sub Pages of Admin Guide / Certificates 
- ['admin-guide/certificates/https.md', '', '']
- ['admin-guide/certificates/saml.md', '', '']
- ['admin-guide/certificates/openid.md', '', '']
- ['admin-guide/certificates/federation.md', '', '']
- ['admin-guide/certificates/ldap.md', '', '']

# Sub pages of Admin Guide / User-Management
- ['admin-guide/user-management/scim.md', '', '']
- ['admin-guide/user-management/ldap-sync.md', '', '']
- ['admin-guide/user-management/local-admin.md', '', '']
- ['admin-guide/user-management/registration.md', '', '']
- ['admin-guide/user-management/self-service.md', '', '']

# Sub pages of Admin Guide / Authentication
- ['admin-guide/authentication/ldap.md', '', '']
- ['admin-guide/authentication/custom.md', '', '']
- ['admin-guide/authentication/oxPush.md', '', '']
- ['admin-guide/authentication/saml.md', '', '']
- ['admin-guide/authentication/cas.md', '', '']
- ['admin-guide/authentication/google.md', '', '']
- ['admin-guide/authentication/duo.md', '', '']
- ['admin-guide/authentication/toopher.md', '', '']

# Sub pages of Admin Guide / SAML
- ['admin-guide/saml/outbound-saml.md', '', '']
- ['admin-guide/saml/inbound-saml.md', '', '']
- ['admin-guide/saml/saml-registration.md', '', '']
- ['admin-guide/saml/saml-sp-configuration.md', '', '']

# Sub Pages of Admin Guide / OpenID Connect
- ['admin-guide/openid-connect/registration.md', '', '']
- ['admin-guide/openid-connect/discovery.md', '', '']
- ['admin-guide/openid-connect/scopes.md', '', '']
- ['admin-guide/openid-connect/client-config.md', '', '']

# Sub pages of Admin Guide / UMA 
- ['admin-guide/uma/discovery.md', '', '']
- ['admin-guide/uma/resource-registration.md', '', '']
- ['admin-guide/uma/policy.md', '', '']
- ['admin-guide/uma/uma-scopes.md', '', '']
- ['admin-guide/uma/mod_ox.md', '', '']

# Sub pages of Admin Guide / Interception Scripts 
- ['admin-guide/interception-scripts/authentication.md', '', '']
- ['admin-guide/interception-scripts/authorization.md', '', '']
- ['admin-guide/interception-scripts/id-generation.md', '', '']
- ['admin-guide/interception-scripts/attribute-transformation.md', '', '']
- ['admin-guide/interception-scripts/post-registration.md', '', '']
- ['admin-guide/interception-scripts/pre-registration.md', '', '']
- ['admin-guide/interception-scripts/logout.md', '', '']
- ['admin-guide/interception-scripts/saml-discovery.md', '', '']

# Sub pages of Admin Guide / oxPush
- ['admin-guide/oxPush/cordova-app.md', '', '']
- ['admin-guide/oxPush/oxPush-server.md', '', '']
- ['admin-guide/oxPush/oxPush-crypto.md', '', '']

# Sub pages of Multiparty Federation 
- ['admin-guide/multiparty-federation/saml-federation.md', '', '']
- ['admin-guide/multiparty-federation/oauth2-federation.md', '', '']
- ['admin-guide/multiparty-federation/federation-public-website.md', '', '']

# Home Page
- ['index.md', '', '']

