site_name: Gluu Server
site_description: An SSO, Federation and API Access Management suite
site_favicon: '/img/gluu_favicon.ico'
copyright: Copyright &copy; 2014, Gluu, Inc.
docs_dir: sources
repo_url: https://github.com/GluuFederation/docs
theme: spacelab 

pages:

# Home Page
- ['index.md', 'Home']

# Articles
- ['./articles/apache-saml/index.md', 'Articles', 'Apache SAML']
- ['articles/java-saml/index.md', 'Articles', 'Java SAML']
- ['articles/apache-oauth2/index.md', 'Articles', 'Apache OpenID Connect / UMA']
- ['articles/nginx-oauth2/index.md', 'Articles', 'nginx OpenID Connect / UMA']
- ['articles/js-connect/index.md', 'Articles', 'JavaScript OpenID Connect RP']
- ['articles/java-connect/index.md', 'Articles', 'Java OpenID Connect RP']
- ['articles/scim-client/index.md', 'Articles', 'Java SCIM client']
- ['articles/mobile-api/index.md', 'Articles', 'Mobile - Headless API : Connect / UMA']

# Reference sections
- ['reference/configuration/index.md', 'Reference', 'Configuration']
- ['reference/ldap/index.md', 'Reference', 'LDAP Schema']
- ['reference/lib/index.md', 'Reference', 'Libraries']
- ['reference/api/index.md', 'Reference', 'APIs']

# Admin Guide Sections
- ['admin-guide/introduction/index.md', 'Admin Guide', 'introduction']
- ['admin-guide/installation/index.md', 'Admin Guide', 'Installation']
- ['admin-guide/configuration/index.md', 'Admin Guide', 'Configuration']
- ['admin-guide/custom-look/index.md', 'Admin Guide', 'Customizing Look and Feel']
- ['admin-guide/certificates/index.md', 'Admin Guide', 'Certificates']
- ['admin-guide/user-management/index.md', 'Admin Guide', 'User Management']
- ['admin-guide/authentication/index.md', 'Admin Guide', 'Authentication']
- ['admin-guide/saml/index.md', 'Admin Guide', 'SAML']
- ['admin-guide/openid-connect/index.md', 'Admin Guide', 'OpenID Connect']
- ['admin-guide/uma/index.md', 'Admin Guide', 'UMA']
- ['admin-guide/interception-scripts/index.md', 'Admin Guide', 'Interception Scripts']
- ['admin-guide/multiparty-federation/index.md', 'Admin Guide', 'MultiParty Federation']
- ['admin-guide/oxPush/index.md', 'Admin Guide', 'oxPush']

# Sub Pages of introduction 
- ['admin-guide/introduction/architecture.md', 'Admin Guide']
- ['admin-guide/introduction/design-goals.md', 'Admin Guide']
- ['admin-guide/introduction/gluu-server-mission.md', 'Admin Guide']
- ['admin-guide/introduction/licenses.md', 'Admin Guide']

# Sub Pages of Admin Guide / installation
- ['admin-guide/installation/redhat.md', 'Admin Guide','**HIDDEN**']
- ['admin-guide/installation/ubuntu.md', 'Admin Guide', '**HIDDEN**']
- ['admin-guide/installation/centos.md', 'Admin Guide', '**HIDDEN**']
- ['admin-guide/installation/debian.md', 'Admin Guide', '**HIDDEN**']
- ['admin-guide/installation/windows.md', 'Admin Guide', '**HIDDEN**']
- ['admin-guide/installation/mac.md', 'Admin Guide']
- ['admin-guide/installation/juju.md', 'Admin Guide']
- ['admin-guide/installation/build.md', 'Admin Guide']

# Sub Pages of Admin Guide / Configuration
- ['admin-guide/configuration/asimba.md', 'Admin Guide']
- ['admin-guide/configuration/oxAuth.md', 'Admin Guide']
- ['admin-guide/configuration/oxPush.md', 'Admin Guide']
- ['admin-guide/configuration/oxTrust.md', 'Admin Guide']
- ['admin-guide/configuration/shibIDP.md', 'Admin Guide']
- ['admin-guide/configuration/oxProx.md', 'Admin Guide']

# Sub Pages of Customizing Look and Feel
- ['admin-guide/custom-look/authentication.md', 'Admin Guide']
- ['admin-guide/custom-look/defaults.md', 'Admin Guide']
- ['admin-guide/custom-look/registration.md', 'Admin Guide']
- ['admin-guide/custom-look/saml-discovery.md', 'Admin Guide']
- ['admin-guide/custom-look/user-profile.md', 'Admin Guide']
- ['admin-guide/custom-look/xhtml.md', 'Admin Guide']

# Sub Pages of Admin Guide / Certificates 
- ['admin-guide/certificates/https.md', 'Admin Guide']
- ['admin-guide/certificates/saml.md', 'Admin Guide']
- ['admin-guide/certificates/openid.md', 'Admin Guide']
- ['admin-guide/certificates/federation.md', 'Admin Guide']
- ['admin-guide/certificates/ldap.md', 'Admin Guide']

# Sub pages of Admin Guide / User-Management
- ['admin-guide/user-management/scim.md', 'Admin Guide']
- ['admin-guide/user-management/ldap-sync.md', 'Admin Guide']
- ['admin-guide/user-management/local-admin.md', 'Admin Guide']
- ['admin-guide/user-management/registration.md', 'Admin Guide']
- ['admin-guide/user-management/self-service.md', 'Admin Guide']
- ['admin-guide/user-management/invitation-code-registration.md', 'Admin Guide']

# Sub pages of Admin Guide / Authentication
- ['admin-guide/authentication/ldap.md', 'Admin Guide']
- ['admin-guide/authentication/custom.md', 'Admin Guide']
- ['admin-guide/authentication/oxPush.md', 'Admin Guide']
- ['admin-guide/authentication/saml.md', 'Admin Guide']
- ['admin-guide/authentication/cas.md', 'Admin Guide']
- ['admin-guide/authentication/google.md', 'Admin Guide']
- ['admin-guide/authentication/duo.md', 'Admin Guide']
- ['admin-guide/authentication/toopher.md', 'Admin Guide']

# Sub pages of Admin Guide / SAML
- ['admin-guide/saml/outbound-saml.md', 'Admin Guide']
- ['admin-guide/saml/inbound-saml.md', 'Admin Guide']
- ['admin-guide/saml/saml-registration.md', 'Admin Guide']
- ['admin-guide/saml/saml-sp-configuration.md', 'Admin Guide']

# Sub Pages of Admin Guide / OpenID Connect
- ['admin-guide/openid-connect/registration.md', 'Admin Guide']
- ['admin-guide/openid-connect/discovery.md', 'Admin Guide']
- ['admin-guide/openid-connect/scopes.md', 'Admin Guide']
- ['admin-guide/openid-connect/client-config.md', 'Admin Guide']

# Sub pages of Admin Guide / UMA 
- ['admin-guide/uma/discovery.md', 'Admin Guide']
- ['admin-guide/uma/resource-registration.md', 'Admin Guide']
- ['admin-guide/uma/policy.md', 'Admin Guide']
- ['admin-guide/uma/uma-scopes.md', 'Admin Guide']
- ['admin-guide/uma/mod_ox.md', 'Admin Guide']

# Sub pages of Admin Guide / Interception Scripts 
- ['admin-guide/interception-scripts/authentication.md', 'Admin Guide']
- ['admin-guide/interception-scripts/authorization.md', 'Admin Guide']
- ['admin-guide/interception-scripts/id-generation.md', 'Admin Guide']
- ['admin-guide/interception-scripts/attribute-transformation.md', 'Admin Guide']
- ['admin-guide/interception-scripts/post-registration.md', 'Admin Guide']
- ['admin-guide/interception-scripts/pre-registration.md', 'Admin Guide']
- ['admin-guide/interception-scripts/logout.md', 'Admin Guide']
- ['admin-guide/interception-scripts/saml-discovery.md', 'Admin Guide']

# Sub pages of Admin Guide / oxPush
- ['admin-guide/oxPush/cordova-app.md', 'Admin Guide']
- ['admin-guide/oxPush/oxPush-server.md', 'Admin Guide']
- ['admin-guide/oxPush/oxPush-crypto.md', 'Admin Guide']

# Sub pages of Multiparty Federation 
- ['admin-guide/multiparty-federation/saml-federation.md', 'Admin Guide']
- ['admin-guide/multiparty-federation/oauth2-federation.md', 'Admin Guide']
- ['admin-guide/multiparty-federation/federation-public-website.md', 'Admin Guide']


# Sub pages of Reference / Library
- ['reference/lib/openid-connect.md', 'Reference']
- ['reference/lib/uma.md', 'Reference']
- ['reference/lib/scim.md', 'Reference']
- ['reference/lib/saml.md', 'Reference']
- ['reference/lib/user-management.md', 'Reference']

# Sub pages of Reference / LDAP
- ['reference/ldap/schema.md', 'Reference']
- ['reference/ldap/namespace.md', 'Reference']
- ['reference/ldap/indexing.md', 'Reference']
- ['reference/ldap/replication.md', 'Reference']

# Sub pages of Reference / Configuration
- ['reference/configuration/system.md', 'Reference']
- ['reference/configuration/oxAuth.md', 'Reference']
- ['reference/configuration/oxTrust.md', 'Reference']
- ['reference/configuration/shibIDP.md', 'Reference']
- ['reference/configuration/asimba.md', 'Reference']
- ['reference/configuration/opendj.md', 'Reference']
- ['reference/configuration/openldap.md', 'Reference']
- ['reference/configuration/jagger.md', 'Reference']
- ['reference/configuration/oxPush.md', 'Reference']
- ['reference/configuration/oxProx.md', 'Reference']
- ['reference/configuration/mysql.md', 'Reference']
- ['reference/configuration/memcached.md', 'Reference']
