site_name: Gluu Server
site_description: An SSO, Federation and API Access Management suite
site_favicon: '/img/gluu_favicon.ico'
copyright: Copyright &copy; 2014, Gluu, Inc.
docs_dir: sources
repo_url: https://github.com/GluuFederation/docs
theme: spacelab 

pages:

# Home Page
- ['./index.md', 'Home']

# Admin Guide Sections
- ['admin-guide/introduction/index.md', 'Admin Guide', 'introduction']
- ['admin-guide/installation/index.md', 'Admin Guide', 'Installation']
- ['admin-guide/configuration/index.md', 'Admin Guide', 'Configuration']
- ['admin-guide/custom-look/index.md', 'Admin Guide', 'Customizing Look and Feel']
- ['admin-guide/certificates/index.md', 'Admin Guide', 'Certificates']
- ['admin-guide/user-management/index.md', 'Admin Guide', 'User Management']
- ['admin-guide/authentication/index.md', 'Admin Guide', 'Authentication']
- ['admin-guide/saml/index.md', 'Admin Guide', 'SAML']
- ['admin-guide/openid-connect/index.md', 'Admin Guide', 'OpenID Connect']
- ['admin-guide/uma/index.md', 'Admin Guide', 'UMA']
- ['admin-guide/interception-scripts/index.md', 'Admin Guide', 'Interception Scripts']
- ['admin-guide/multiparty-federation/index.md', 'Admin Guide', 'MultiParty Federation']
- ['admin-guide/oxPush/index.md', 'Admin Guide', 'oxPush']

# Reference sections
- ['reference/configuration/index.md', 'Reference', 'Configuration']
- ['reference/oxTrust/index.md', 'Reference', 'oxTrust User Interface']
- ['reference/ldap/index.md', 'Reference', 'LDAP Schema']
- ['reference/lib/index.md', 'Reference', 'Libraries']
- ['reference/api/index.md', 'Reference', 'APIs']

# Articles
- ['articles/apache-saml.md', 'Articles', 'Apache SAML']
- ['articles/java-saml.md', 'Articles', 'Java SAML']
- ['articles/apache-oauth2.md', 'Articles', 'Apache OpenID Connect / UMA']
- ['articles/nginx-oauth2.md', 'Articles', 'nginx OpenID Connect / UMA']
- ['articles/js-connect.md', 'Articles', 'JavaScript OpenID Connect RP']
- ['articles/java-connect.md', 'Articles', 'Java OpenID Connect RP']
- ['articles/scim-client.md', 'Articles', 'Java SCIM client']
- ['articles/mobile-api.md', 'Articles', 'Mobile - Headless API : Connect / UMA']

# Sub Pages of introduction 
- ['admin-guide/introduction/architecture.md', 'Admin Guide', 'introduction', 'architecture']
- ['admin-guide/introduction/design-goals.md', 'Admin Guide', 'introduction', 'design-goals']
- ['admin-guide/introduction/gluu-server-mission.md', 'Admin Guide', 'introduction', 'gluu-server-mission']
- ['admin-guide/introduction/history.md', 'Admin Guide', 'introduction', 'history']
- ['admin-guide/introduction/licenses.md', 'Admin Guide', 'introduction', 'licenses']

# Sub Pages of Admin Guide / installation
- ['admin-guide/installation/redhat.md', 'Admin Guide', 'Installation', 'redhat']
- ['admin-guide/installation/ubuntu.md', 'Admin Guide', 'Installation', 'ubuntu']
- ['admin-guide/installation/centos.md', 'Admin Guide', 'Installation', 'centos']
- ['admin-guide/installation/debian.md', 'Admin Guide', 'Installation', 'debian']
- ['admin-guide/installation/windows.md', 'Admin Guide', 'Installation', 'windows']
- ['admin-guide/installation/mac.md', 'Admin Guide', 'Installation', 'mac']
- ['admin-guide/installation/juju.md', 'Admin Guide', 'Installation', 'juju']
- ['admin-guide/installation/build.md', 'Admin Guide', 'Installation', 'build']

# Sub Pages of Admin Guide / Configuration
- ['admin-guide/configuration/asimba.md', 'Admin Guide', 'Configuration', 'asimba']
- ['admin-guide/configuration/oxAuth.md', 'Admin Guide', 'Configuration', 'oxAuth']
- ['admin-guide/configuration/oxPush.md', 'Admin Guide', 'Configuration', 'oxPush']
- ['admin-guide/configuration/oxTrust.md', 'Admin Guide', 'Configuration', 'oxTrust']
- ['admin-guide/configuration/shibIDP.md', 'Admin Guide', 'Configuration', 'shibIDP']
- ['admin-guide/configuration/oxProx.md', 'Admin Guide', 'Configuration', 'oxProx']

# Sub Pages of Customizing Look and Feel
- ['admin-guide/custom-look/authentication.md', 'Admin Guide', 'Customizing Look and Feel', 'authentication']
- ['admin-guide/custom-look/defaults.md', 'Admin Guide', 'Customizing Look and Feel', 'defaults']
- ['admin-guide/custom-look/registration.md', 'Admin Guide', 'Customizing Look and Feel', 'registration']
- ['admin-guide/custom-look/saml-discovery.md', 'Admin Guide', 'Customizing Look and Feel', 'saml-discovery']
- ['admin-guide/custom-look/user-profile.md', 'Admin Guide', 'Customizing Look and Feel', 'user-profile']
- ['admin-guide/custom-look/xhtml.md', 'Admin Guide', 'Customizing Look and Feel', 'xhtml']

# Sub Pages of Admin Guide / Certificates 
- ['admin-guide/certificates/https.md', 'Admin Guide', 'Certificates', 'https']
- ['admin-guide/certificates/saml.md', 'Admin Guide', 'Certificates', 'saml']
- ['admin-guide/certificates/openid.md', 'Admin Guide', 'Certificates', 'openid']
- ['admin-guide/certificates/federation.md', 'Admin Guide', 'Certificates', 'federation']
- ['admin-guide/certificates/ldap.md', 'Admin Guide', 'Certificates', 'ldap']

# Sub pages of Admin Guide / User-Management
- ['admin-guide/user-management/scim.md', 'Admin Guide', 'User Management', 'scim']
- ['admin-guide/user-management/ldap-sync.md', 'Admin Guide', 'User Management', 'ldap-sync']
- ['admin-guide/user-management/local-admin.md', 'Admin Guide', 'User Management', 'local-admin']
- ['admin-guide/user-management/registration.md', 'Admin Guide', 'User Management', 'registration']
- ['admin-guide/user-management/self-service.md', 'Admin Guide', 'User Management', 'self-service']
- ['admin-guide/user-management/invitation-code-registration.md', 'Admin Guide', 'User Management', 'invitation-code-registration']

# Sub pages of Admin Guide / Authentication
- ['admin-guide/authentication/ldap.md', 'Admin Guide', 'Authentication', 'ldap']
- ['admin-guide/authentication/custom.md', 'Admin Guide', 'Authentication', 'custom']
- ['admin-guide/authentication/oxPush.md', 'Admin Guide', 'Authentication', 'oxPush']
- ['admin-guide/authentication/saml.md', 'Admin Guide', 'Authentication', 'saml']
- ['admin-guide/authentication/cas.md', 'Admin Guide', 'Authentication', 'cas']
- ['admin-guide/authentication/google.md', 'Admin Guide', 'Authentication', 'google']
- ['admin-guide/authentication/duo.md', 'Admin Guide', 'Authentication', 'duo']
- ['admin-guide/authentication/toopher.md', 'Admin Guide', 'Authentication', 'toopher']

# Sub pages of Admin Guide / SAML
- ['admin-guide/saml/outbound-saml.md', 'Admin Guide', 'SAML', 'outbound-saml']
- ['admin-guide/saml/inbound-saml.md', 'Admin Guide', 'SAML', 'inbound-saml']
- ['admin-guide/saml/saml-registration.md', 'Admin Guide', 'SAML', 'saml-registration']
- ['admin-guide/saml/saml-sp-configuration.md', 'Admin Guide', 'SAML', 'saml-sp-configuration']

# Sub Pages of Admin Guide / OpenID Connect
- ['admin-guide/openid-connect/registration.md', 'Admin Guide', 'OpenID Connect', 'registration']
- ['admin-guide/openid-connect/discovery.md', 'Admin Guide', 'OpenID Connect', 'discovery']
- ['admin-guide/openid-connect/scopes.md', 'Admin Guide', 'OpenID Connect', 'scopes']
- ['admin-guide/openid-connect/client-config.md', 'Admin Guide', 'OpenID Connect', 'client-config']

# Sub pages of Admin Guide / UMA 
- ['admin-guide/uma/discovery.md', 'Admin Guide', 'UMA', 'discovery']
- ['admin-guide/uma/resource-registration.md', 'Admin Guide', 'UMA', 'resource-registration']
- ['admin-guide/uma/policy.md', 'Admin Guide', 'UMA', 'policy']
- ['admin-guide/uma/uma-scopes.md', 'Admin Guide', 'UMA', 'uma-scopes']
- ['admin-guide/uma/mod_ox.md', 'Admin Guide', 'UMA', 'mod_ox']

# Sub pages of Admin Guide / Interception Scripts 
- ['admin-guide/interception-scripts/authentication.md', 'Admin Guide', 'Interception Scripts ', 'authentication']
- ['admin-guide/interception-scripts/authorization.md', 'Admin Guide', 'Interception Scripts ', 'authorization']
- ['admin-guide/interception-scripts/id-generation.md', 'Admin Guide', 'Interception Scripts ', 'id-generation']
- ['admin-guide/interception-scripts/attribute-transformation.md', 'Admin Guide', 'Interception Scripts ', 'attribute-transformation']
- ['admin-guide/interception-scripts/post-registration.md', 'Admin Guide', 'Interception Scripts ', 'post-registration']
- ['admin-guide/interception-scripts/pre-registration.md', 'Admin Guide', 'Interception Scripts ', 'pre-registration']
- ['admin-guide/interception-scripts/logout.md', 'Admin Guide', 'Interception Scripts ', 'logout']
- ['admin-guide/interception-scripts/saml-discovery.md', 'Admin Guide', 'Interception Scripts ', 'saml-discovery']

# Sub pages of Admin Guide / oxPush
- ['admin-guide/oxPush/cordova-app.md', 'Admin Guide', 'oxPush', 'cordova-app']
- ['admin-guide/oxPush/oxPush-server.md', 'Admin Guide', 'oxPush', 'oxPush-server']
- ['admin-guide/oxPush/oxPush-crypto.md', 'Admin Guide', 'oxPush', 'oxPush-crypto']

# Sub pages of Multiparty Federation 
- ['admin-guide/multiparty-federation/saml-federation.md', 'Admin Guide', 'Multiparty Federation ', 'saml-federation']
- ['admin-guide/multiparty-federation/oauth2-federation.md', 'Admin Guide', 'Multiparty Federation ', 'oauth2-federation']
- ['admin-guide/multiparty-federation/federation-public-website.md', 'Admin Guide', 'Multiparty Federation ', 'federation-public-website']

- ['reference/lib/openid-connect.md', 'Reference', 'Libraries', 'openid-connect']
- ['reference/lib/uma.md', 'Reference', 'Libraries', 'uma']
- ['reference/lib/scim.md', 'Reference', 'Libraries', 'scim']
- ['reference/lib/saml.md', 'Reference', 'Libraries', 'saml']
- ['reference/lib/user-management.md', 'Reference', 'Libraries', 'user-management']

# Sub pages of Reference / LDAP
- ['reference/ldap/opendj-schema.md', 'Reference', 'LDAP Schema', 'opendj-schema']
- ['reference/ldap/openldap-schema.md', 'Reference', 'LDAP Schema', 'openldap-schema']
- ['reference/ldap/389ds-schema.md', 'Reference', 'LDAP Schema', '389ds-schema']
- ['reference/ldap/namespace.md', 'Reference', 'LDAP Schema', 'namespace']
- ['reference/ldap/indexing.md', 'Reference', 'LDAP Schema', 'indexing']
- ['reference/ldap/replication.md', 'Reference', 'LDAP Schema', 'replication']

# Sub pages of Reference / Configuration
- ['reference/configuration/system.md', 'Reference', 'Configuration', 'system']
- ['reference/configuration/oxAuth.md', 'Reference', 'Configuration', 'oxAuth']
- ['reference/configuration/oxTrust.md', 'Reference', 'Configuration', 'oxTrust']
- ['reference/configuration/shibIDP.md', 'Reference', 'Configuration', 'shibIDP']
- ['reference/configuration/asimba.md', 'Reference', 'Configuration', 'asimba']
- ['reference/configuration/opendj.md', 'Reference', 'Configuration', 'opendj']
- ['reference/configuration/openldap.md', 'Reference', 'Configuration', 'openldap']
- ['reference/configuration/jagger.md', 'Reference', 'Configuration', 'jagger']
- ['reference/configuration/oxPush.md', 'Reference', 'Configuration', 'oxPush']
- ['reference/configuration/oxProx.md', 'Reference', 'Configuration', 'oxProx']
- ['reference/configuration/mysql.md', 'Reference', 'Configuration', 'mysql']
- ['reference/configuration/memcached.md', 'Reference', 'Configuration', 'memcached']

# Sub pages of Reference / oxTrust
- ['reference/oxTrust/configuration.md', 'Reference', 'oxTrust User Interface', 'configuration']
- ['reference/oxTrust/oauth2.md', 'Reference', 'oxTrust User Interface', 'oauth2']
- ['reference/oxTrust/personal.md', 'Reference', 'oxTrust User Interface', 'personal']
- ['reference/oxTrust/saml.md', 'Reference', 'oxTrust User Interface', 'saml']
- ['reference/oxTrust/users.md', 'Reference', 'oxTrust User Interface', 'users']
